# Generated by Django 3.1.3 on 2020-12-01 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raterapi', '0002_auto_20201121_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecategory',
            name='player',
        ),
        migrations.AddField(
            model_name='gamecategory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='raterapi.categories'),
            preserve_default=False,
        ),
    ]
