# Generated by Django 3.1.3 on 2020-12-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterapi', '0003_auto_20201201_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='categories',
            field=models.ManyToManyField(related_name='game_categories', related_query_name='game_category', to='raterapi.Categories'),
        ),
    ]
