# Generated by Django 3.1.3 on 2020-12-04 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raterapi', '0004_game_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', related_query_name='review', to='raterapi.game'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', related_query_name='review', to='raterapi.player'),
        ),
    ]
