# Generated by Django 3.1.4 on 2020-12-07 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raterapi', '0005_auto_20201204_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='images',
            name='player',
        ),
        migrations.AddField(
            model_name='images',
            name='action_pic',
            field=models.ImageField(null=True, upload_to='actionimages'),
        ),
        migrations.AlterField(
            model_name='images',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pictures', to='raterapi.game'),
        ),
    ]
