# Generated by Django 3.1.4 on 2020-12-07 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raterapi', '0006_auto_20201207_0150'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
